spring.application.name=doAn2026
spring.datasource.url=jdbc:postgresql://localhost:5432/MSME-DATABASE
spring.datasource.username=postgres
spring.datasource.password=vh692004
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
app.jwt.secret=Q2h1eWVuVmllbktpbmhEb2FuaFdvbkdyb3VwRG9BblBob25nS2hhbTIwMjZTaWV1QmFvTWF0XzI1Nl9iaXQ=
app.jwt.expiration-ms=86400000